version: '3'

services:
  bitcoin-negotiation-jvm: 
    image: quarkus/bitcoin-negotiation-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-bitcoin-negotiation:3306/bitcoin_negotiation?autoReconnect=true
    networks:
      - mysql-db    
    ports:
      - 8080:8080
    depends_on:
      - mysql-bitcoin-negotiation

  mysql-bitcoin-negotiation: 
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bitcoin_negotiation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.bitcoin.negotiation:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

networks:
 mysql-db:
  driver: bridge

volumes:
  mysql.bitcoin.negotiation:
